name: swggrmm
options:
  bundleIdPrefix: com.maga4208
  deploymentTarget:
    iOS: 13.0
targets:
  swggrmm:
    type: application
    platform: iOS
    sources: [SimpleIOSApp]
    dependencies:
      - package: TDLibKit
        product: TDLibKit
    settings:
      # Эти строчки — самое важное. Они говорят Xcode, где искать библиотеки.
      FRAMEWORK_SEARCH_PATHS: $(inherited) $(BUILD_DIR)/Release-iphoneos
      HEADER_SEARCH_PATHS: $(inherited) $(BUILD_DIR)/Release-iphoneos/include
    info:
      path: SimpleIOSApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: swggrmm
        CFBundleDisplayName: swggrmm
packages:
  TDLibKit:
    url: https://github.com/Swiftgram/TDLibKit
    branch: main
